### ISSUE TITLE
Uploading files fail when large files are used and does not recover

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/radar-upload-source-connector#93]
The backend  timeout or fails when we try to upload a large file (80MB). 
Afterwards when we try to upload a new file to the same record, the server throws the error below and does not respond to future requests. 

```
2019-12-18 11:23:49 UTC [-0] ERROR - [500] http://radarbase.bmrc.ox.ac.uk:80/records/67/contents/201912181127_max_altoida.com_213_0.zip [org.radarbase.jersey.exception.mapper.UnhandledExceptionMapper:28] 
javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: unable to merge BLOB data
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:922)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:881)
	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:261)
	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:492)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:416)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:525)
	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:456)
	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:419)
	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151)
	at org.hibernate.event.internal.DefaultMergeEventListener.cascadeOnMerge(DefaultMergeEventListener.java:519)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsPersistent(DefaultMergeEventListener.java:204)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:178)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:70)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:889)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:875)
	at org.radarbase.upload.doa.RecordRepositoryImpl$updateContent$1.invoke(RecordRepositoryImpl.kt:160)
	at org.radarbase.upload.doa.RecordRepositoryImpl$updateContent$1.invoke(RecordRepositoryImpl.kt:45)
	at org.radarbase.upload.doa.EntityManagerExtensionsKt$transact$1.invoke(EntityManagerExtensions.kt:13)
	at org.radarbase.upload.doa.EntityManagerExtensionsKt$transact$1.invoke(EntityManagerExtensions.kt)
	at org.radarbase.upload.doa.EntityManagerExtensionsKt.createTransaction(EntityManagerExtensions.kt:25)
	at org.radarbase.upload.doa.EntityManagerExtensionsKt.transact(EntityManagerExtensions.kt:12)
	at org.radarbase.upload.doa.RecordRepositoryImpl.updateContent(RecordRepositoryImpl.kt:138)
	at org.radarbase.upload.resource.RecordResource.putContents(RecordResource.kt:181)
	at jdk.internal.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.hibernate.exception.GenericJDBCException: unable to merge BLOB data
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.dialect.Dialect$3.mergeBlob(Dialect.java:620)
	at org.hibernate.type.BlobType.getReplacement(BlobType.java:39)
	at org.hibernate.type.BlobType.getReplacement(BlobType.java:20)
	at org.hibernate.type.AbstractStandardBasicType.replace(AbstractStandardBasicType.java:354)
	at org.hibernate.type.TypeHelper.replace(TypeHelper.java:167)
	at org.hibernate.event.internal.DefaultMergeEventListener.copyValues(DefaultMergeEventListener.java:451)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsPersistent(DefaultMergeEventListener.java:205)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:178)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:911)
	... 49 common frames omitted
Caused by: org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode.
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:254)
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:240)
	at org.postgresql.jdbc.AbstractBlobClob.getLo(AbstractBlobClob.java:272)
	at org.postgresql.jdbc.AbstractBlobClob.getBinaryStream(AbstractBlobClob.java:116)
	at jdk.internal.reflect.GeneratedMethodAccessor276.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.hibernate.engine.jdbc.SerializableBlobProxy.invoke(SerializableBlobProxy.java:60)
	at com.sun.proxy.$Proxy81.getBinaryStream(Unknown Source)
	at org.hibernate.dialect.Dialect$3.mergeBlob(Dialect.java:617)
	... 57 common frames omitted

```

**Comment by nivemaham** [comment]
We can upload upto 1GB now. Will reopen if we notice this issue again
